stages:
  data_ingestion:
    cmd: python src/LSTM_BTC_Prediction/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/LSTM_BTC_Prediction/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_preprocessing:
    cmd: python src/LSTM_BTC_Prediction/pipeline/stage_02_data_preprocessing.py
    deps: 
      - src/LSTM_BTC_Prediction/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion
    params:
      - LOOK_BACK
      - FORECAST_HORIZON
    outs:
      - artifacts/data_split/test.csv
      - artifacts/data_split/train.csv
      - artifacts/data_split/val.csv
      - artifacts/data_scaled/test_scaled.csv
      - artifacts/data_scaled/train_scaled.csv
      - artifacts/data_scaled/val_scaled.csv
      - artifacts/data_final/testX.npy
      - artifacts/data_final/testY.npy
      - artifacts/data_final/trainX.npy
      - artifacts/data_final/trainY.npy
      - artifacts/data_final/valX.npy
      - artifacts/data_final/valY.npy

  prepare_base_model:
    cmd: python src/LSTM_BTC_Prediction/pipeline/stage_03_prepare_base_model.py
    deps: 
      - src/LSTM_BTC_Prediction/pipeline/stage_03_prepare_base_model.py
      - config/config.yaml
      - artifacts/data_final/trainX.npy
    params:
      - LSTM_UNITS_1
      - LSTM_UNITS_2
      - DROPOUT_RATE_1
      - DROPOUT_RATE_2
      - L2_REG_1
      - L2_REG_2 
    outs:
      - artifacts/prepare_base_model/full_model.h5

  model_training:
    cmd: python src/LSTM_BTC_Prediction/pipeline/stage_04_model_training.py
    deps:
      - src/LSTM_BTC_Prediction/pipeline/stage_04_model_training.py
      - config/config.yaml
      - artifacts/prepare_base_model/full_model.h5
      - artifacts/data_split/test.csv
      - artifacts/data_split/train.csv
      - artifacts/data_split/val.csv
      - artifacts/data_final/testX.npy
      - artifacts/data_final/testY.npy
      - artifacts/data_final/trainX.npy
      - artifacts/data_final/trainY.npy
      - artifacts/data_final/valX.npy
      - artifacts/data_final/valY.npy
    params:
      - BATCH_SIZE
      - EPOCHS
      - LEARNING_RATE
      - PATIENCE
    outs:
      - artifacts/training/model.keras
    metrics:
      - scores.json:
          cache: false