BATCH_SIZE: 30
CURRENT_DATE: '2024-06-02'
DROPOUT_RATE_1: 0.1
DROPOUT_RATE_2: 0.1
EPOCHS: 100
FORECAST_HORIZON: 1
L2_REG_1: 0.001
L2_REG_2: 0.001
LEARNING_RATE: 0.001
LOOK_BACK: 120
LSTM_UNITS_1: 356
LSTM_UNITS_2: 356
PATIENCE: 10
