LOOK_BACK : 120
FORECAST_HORIZON : 1
LSTM_UNITS_1: 156
LSTM_UNITS_2 : 124
DROPOUT_RATE_1: 0.1
DROPOUT_RATE_2: 0.1
BATCH_SIZE: 30
EPOCHS: 1
LEARNING_RATE: 0.001
PATIENCE : 10
L2_REG_1 : 0.001
L2_REG_2 : 0.001