BATCH_SIZE: 30
CURRENT_DATE: '2024-05-10'
DROPOUT_RATE_1: 0.1
DROPOUT_RATE_2: 0.1
EPOCHS: 1
FORECAST_HORIZON: 1
L2_REG_1: 0.001
L2_REG_2: 0.001
LEARNING_RATE: 0.001
LOOK_BACK: 120
LSTM_UNITS_1: 156
LSTM_UNITS_2: 124
PATIENCE: 10
